=== DanielFernandezR/vlc-random-playlist/library.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Lenguaje de Marcas-->
<!-- Tasca 3.1 Creación de un archivo XSD para validar el XML del proyecto VLC-->
<!-- José Jiménez Beltrán y Daniel Fernández Rodríguez -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="library">
  <!-- El elemento library es un complexType porque contiene otros elementos -->
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tracks"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="tracks">
  <!-- El elemento tracks es un complexType porque contiene otros elementos -->
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="track"/>
        <!-- El elemento track es unbounded ya que no hay limite en las veces que puede salir -->
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="track">
  <!-- El elemento track es un complexType porque contiene otros elementos -->
    <xs:complexType>
      <xs:sequence>
      <!-- Track esta en sequence ya que queremos que los datos salgan de manera ordenada -->
        <xs:element ref="id"/>
        <xs:element ref="name"/>
        <xs:element ref="miliseconds"/>
        <xs:element ref="bytes"/>
        <xs:element ref="path"/>
        <xs:element ref="media_type"/>
        <xs:element ref="genres"/>
        <xs:element ref="artists"/>
        <xs:element ref="composers"/>
        <xs:element ref="albums"/>
        <xs:element ref="playlists"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- miliseconds, bytes y path son simpleType ya que no contienen otros elementos ni atributos -->
  <xs:element name="miliseconds" type="xs:integer"/> <!-- Es integer ya que solo contendrá números-->
  <xs:element name="bytes" type="xs:integer"/> <!-- Es integer ya que solo contendrá números-->
  <xs:element name="path" type="xs:string"/> <!-- Es string ya que contendrá una cadena de caracteres-->
  <xs:element name="media_type">
  <!-- El elemento media_type es un complexType porque contiene otros elementos -->
    <xs:complexType>
      <xs:sequence>
      <!-- media_type esta en sequence ya que queremos que los datos salgan de manera ordenada -->
        <xs:element ref="id"/>
        <xs:element ref="name"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="genres">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="genre"/>
        <!-- El elemento genre es unbounded ya que no hay limite en las veces que puede salir-->
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="genre">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="id"/>
        <xs:element ref="name"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="artists">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="artist"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="artist">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="id"/>
        <xs:element ref="name"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="composers">
  <!-- Artists, composers, albums son complexType ya que contienen otros elementos-->
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="composer"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="composer">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="id"/>
        <xs:element ref="name"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="albums">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="album"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="album">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="id"/>
        <xs:element ref="title"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Dentro del elemento title solo puede haber string-->
  <!-- title es simpleType ya que no contiene otros elementos ni atributos -->
  <xs:element name="title" type="xs:string"/>
  <xs:element name="playlists">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="playlist"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="playlist">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="id"/>
        <xs:element ref="name"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Todos los elementos llamados id serán integer, gracias a la referencia (ref) -->
  <xs:element name="id" type="xs:integer"/>
  <!-- Todos los elementos llamados name serán string, gracias a la referencia (ref) -->
  <xs:element name="name" type="xs:string"/>
</xs:schema>

=== DanielFernandezR/vlc-random-playlist/library.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="library.xsd">
<!--Nombre asignatura: Lenguaje de Marcas-->
<!--Nombre del trabajo: Tasca 2.2 Creació d'un fitxer XML pel projecte VLC-->
<!--Nombre del autor: Daniel Fernández Rodríguez y José Jiménez Beltrán-->
    <tracks> <!-- La estructura de nuestro XML se basa en que dentro de canciones esten 
                  todas las relaciones con los otros campos (estructura jerarquica) -->
        <track>
            <id>1</id>
            <name>e_01_Betty_Boop.mp3</name>
            <miliseconds>360000</miliseconds> <!-- Es la duración de la canción -->
            <bytes>4194304</bytes>
            <path>canciones\e_01_Betty_Boop.mp3</path>
            <media_type> <!-- Es el tipo de archivo de la canción. El id se puede repetir. -->
                <id>1</id>
                <name>mp3</name>
            </media_type>
            <genres> <!-- Aqui escribimos los generos que la canción tenga. -->
                <genre>
                    <id>1</id>
                    <name>Electro</name>
                </genre>
            </genres>
            <artists> 
                <artist>
                    <id>1</id>
                    <name>Charlie Puth</name>
                </artist>
            </artists>
            <composers>
                <composer>
                    <id>1</id>
                    <name>Charlie Puth</name>
                </composer>
            </composers>
            <albums> <!-- El album puede contener varias canciones -->
                <album>
                    <id>1</id>
                    <title>Spinnin Records Dance</title>
                </album>
            </albums>
            <playlists> <!-- La playlist se puede asociar a muchas canciones y viceversa -->
                <playlist>
                    <id>1</id>
                    <name>Canciones EDM</name>
                </playlist>
            </playlists>
        </track>
        <track>
            <id>2</id>
            <name>e_02_Waiting_For_Love.mp3</name>
            <miliseconds>289485</miliseconds> <!-- Es la duración de la canción -->
            <bytes>4230541</bytes>
            <path>canciones\e_02_Waiting_For_Love.mp3</path>
            <media_type> <!-- Es el tipo de archivo de la canción. El id se puede repetir. -->
                <id>1</id>
                <name>mp3</name>
            </media_type>
            <genres> <!-- Aqui escribimos los generos que la canción tenga. -->
                <genre>
                    <id>1</id>
                    <name>Electro</name>
                </genre>
            </genres>
            <artists> 
                <artist>
                    <id>2</id>
                    <name>Avicii</name>
                </artist>
            </artists>
            <composers>
                <composer>
                    <id>2</id>
                    <name>Avicii</name>
                </composer>
            </composers>
            <albums> <!-- El album puede contener varias canciones -->
                <album>
                    <id>1</id>
                    <title>Spinnin Records Dance</title>
                </album>
            </albums>
            <playlists> <!-- La playlist se puede asociar a muchas canciones y viceversa -->
                <playlist>
                    <id>1</id>
                    <name>Canciones EDM</name>
                </playlist>
            </playlists>
        </track>
        <track>
            <id>3</id>
            <name>e_03_Animals.mp3</name>
            <miliseconds>378200</miliseconds> <!-- Es la duración de la canción -->
            <bytes>3987258</bytes>
            <path>canciones\e_03_Animals.mp3</path>
            <media_type> <!-- Es el tipo de archivo de la canción. El id se puede repetir. -->
                <id>1</id>
                <name>mp3</name>
            </media_type>
            <genres> <!-- Aqui escribimos los generos que la canción tenga. -->
                <genre>
                    <id>1</id>
                    <name>Electro</name>
                </genre>
            </genres>
            <artists> 
                <artist>
                    <id>3</id>
                    <name>Martin Garrix</name>
                </artist>
            </artists>
            <composers>
                <composer>
                    <id>3</id>
                    <name>Martin Garrix</name>
                </composer>
            </composers>
            <albums> <!-- El album puede contener varias canciones -->
                <album>
                    <id>1</id>
                    <title>Spinnin Records Dance</title>
                </album>
            </albums>
            <playlists> <!-- La playlist se puede asociar a muchas canciones y viceversa -->
                <playlist>
                    <id>1</id>
                    <name>Canciones EDM</name>
                </playlist>
            </playlists>
        </track>
        <track>
            <id>4</id>
            <name>e_04_Beautiful_Now.mp3</name>
            <miliseconds>486258</miliseconds> <!-- Es la duración de la canción -->
            <bytes>3258716</bytes>
            <path>canciones\e_04_Beautiful_Now.mp3</path>
            <media_type> <!-- Es el tipo de archivo de la canción. El id se puede repetir. -->
                <id>1</id>
                <name>mp3</name>
            </media_type>
            <genres> <!-- Aqui escribimos los generos que la canción tenga. -->
                <genre>
                    <id>1</id>
                    <name>Electro</name>
                </genre>
            </genres>
            <artists> 
                <artist>
                    <id>4</id>
                    <name>Zedd</name>
                </artist>
            </artists>
            <composers>
                <composer>
                    <id>4</id>
                    <name>Zedd</name>
                </composer>
            </composers>
            <albums> <!-- El album puede contener varias canciones -->
                <album>
                    <id>1</id>
                    <title>Spinnin Records Dance</title>
                </album>
            </albums>
            <playlists> <!-- La playlist se puede asociar a muchas canciones y viceversa -->
                <playlist>
                    <id>1</id>
                    <name>Canciones EDM</name>
                </playlist>
            </playlists>
        </track>
        <track>
            <id>5</id>
            <name>e_05_Find_You.mp3</name>
            <miliseconds>289542</miliseconds> <!-- Es la duración de la canción -->
            <bytes>3876504</bytes>
            <path>canciones\e_05_Find_You.mp3</path>
            <media_type> <!-- Es el tipo de archivo de la canción. El id se puede repetir. -->
                <id>1</id>
                <name>mp3</name>
            </media_type>
            <genres> <!-- Aqui escribimos los generos que la canción tenga. -->
                <genre>
                    <id>1</id>
                    <name>Electro</name>
                </genre>
            </genres>
            <artists> 
                <artist>
                    <id>4</id>
                    <name>Zedd</name>
                </artist>
            </artists>
            <composers>
                <composer>
                    <id>4</id>
                    <name>Zedd</name>
                </composer>
            </composers>
            <albums> <!-- El album puede contener varias canciones -->
                <album>
                    <id>1</id>
                    <title>Spinnin Records Dance</title>
                </album>
            </albums>
            <playlists> <!-- La playlist se puede asociar a muchas canciones y viceversa -->
                <playlist>
                    <id>1</id>
                    <name>Canciones EDM</name>
                </playlist>
            </playlists>
        </track>
        <track>
            <id>6</id>
            <name>m_01_Hail_to_the_King.mp3</name>
            <miliseconds>503678</miliseconds> <!-- Es la duración de la canción -->
            <bytes>5978423</bytes>
            <path>canciones\m_01_Hail_to_the_King.mp3</path>
            <media_type> <!-- Es el tipo de archivo de la canción. El id se puede repetir. -->
                <id>1</id>
                <name>mp3</name>
            </media_type>
            <genres> <!-- Aqui escribimos los generos que la canción tenga. -->
                <genre>
                    <id>2</id>
                    <name>Metal</name>
                </genre>
            </genres>
            <artists> 
                <artist>
                    <id>5</id>
                    <name>Avenged Sevenfold</name>
                </artist>
            </artists>
            <composers>
                <composer>
                    <id>5</id>
                    <name>Avenged Sevenfold</name>
                </composer>
            </composers>
            <albums> <!-- El album puede contener varias canciones -->
                <album>
                    <id>2</id>
                    <title>Hail to the King</title>
                </album>
            </albums>
            <playlists> <!-- La playlist se puede asociar a muchas canciones y viceversa -->
                <playlist>
                    <id>2</id>
                    <name>Lista Metalera</name>
                </playlist>
            </playlists>
        </track>
        <track>
            <id>7</id>
            <name>m_02_The_Sound_Of_Silence.mp3</name>
            <miliseconds>452698</miliseconds> <!-- Es la duración de la canción -->
            <bytes>4268423</bytes>
            <path>canciones\m_02_The_Sound_Of_Silence.mp3</path>
            <media_type> <!-- Es el tipo de archivo de la canción. El id se puede repetir. -->
                <id>1</id>
